[phases.setup]
nixPkgs = ["...", "maven", "jdk17"]

[phases.build]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/club-management-0.0.1-SNAPSHOT.jar"
