# Configuración para el backend
[environments.production.services.club-manegament]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
watchPatterns = ["backend/**"]

[environments.production.services.club-manegament.deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Configuración para el frontend
[environments.production.services.club-management-frontend]
builder = "DOCKERFILE"
dockerfilePath = "frontend/Dockerfile"
watchPatterns = ["frontend/**"]

[environments.production.services.club-management-frontend.build.buildArgs]
VITE_API_URL = "${{VITE_API_URL}}"

[environments.production.services.club-management-frontend.deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
